### ISSUE TITLE
non-thread-safe usage of SimpleDateFormat

### ISSUE THREAD

**Issue by jsharper** [duosecurity/duo_client_java#1]
In com.duosecurity.client.Http, there's a static instance of SimpleDateFormat, RFC_2822_DATE_FORMAT,  that is used in method signRequest.  SimpleDateFormat is not thread safe, and therefore this usage can cause serious issues when used in a multi-threaded app (like a j2ee web app).  For example, see http://www.codefutures.com/weblog/andygrove/2007/10/simpledateformat-and-thread-safety.html

**Comment by jsharper** [comment]
Note the commit did not fix the issue; the issue is still present.

**Comment by ben-duo** [comment]
Yes, oops, that was obvious when I read my code again! I'll get a fix pushed soon.

**Comment by ben-duo** [comment]
Thanks again! Please let me know if 5f185cd6dd2fd0953541f8610f0e7e58885be2e5 helps.
