### ISSUE TITLE
Version numbers and tags

### ISSUE THREAD

**Issue by rfrovarp** [duosecurity/duo_client_java#23]
Version 0.3.0 isn't tagged, and the version in your master branch is 0.3.0, which is clearly shouldn't be as there have been changes to it since the version number was changed. It should be 0.3.1-SNAPSHOT indicating that it isn't released code. Using mvn release:prepare and mvn release:perform on the repo will do all of the pom version changing and tagging instead of having to do it manual like you did for #9.

**Comment by AaronAtDuo** [comment]
We've fixed up the version numbers, and done the 0.4.0 release along the way.  We'll do our best to keep the versioning correct going forward.  Thanks for your patience, and thanks for using Duo!
