### ISSUE TITLE
Authentication logs limits

### ISSUE THREAD

**Issue by NeQuissimus** [duosecurity/duo_client_java#3]
I am having issues with the Authentication Logs API (`/admin/v1/logs/authentication`).

It seems there is an (as far as I can tell) undocumented limit on it.
I use the SDK as follows:

```scala
import com.duosecurity.client.Http

val user = "api-xxxxx.duosecurity.com"
val integrationKey = "MYTOKEN"
val secret = "MYSECRET"
val http = new Http("GET", user, "/admin/v1/logs/authentication")
http.addParam("minTime", "0")
http.signRequest(integrationKey, secret)
val response = http.executeRequest
```

If I run this faster than once every 30s the API returns me 

```scala
java.lang.Exception: Duo error code (42901): Too Many Requests
  com.duosecurity.client.Http.executeRequest(Http.java:62)
```

a) Where can I find how many is "too many" requests?
b) Should the SDK not at least retry?
c) How come `/admin/v1/logs/administrator` does not have this limitation?

Thank you!

**Comment by adrikim** [comment]
Hey Tim! Thanks for raising the issue. This is probably something that support@duo.com can help you out with better than we can- shoot them an email and they'll be happy to help :)
