### ISSUE TITLE
Versioning question

### ISSUE THREAD

**Issue by oulman** [duosecurity/duo_client_java#9]
Hi, 

It looks like latest release is v0.2.2 but the version within pom.xml for the duo-client is still v0.2.1. When I build from the source the .jar I maven creates is versioned with v0.2.1. Is this expected?

https://github.com/duosecurity/duo_client_java/blob/44204bd86f37d0ca7cbf5e8e821b8f5f7642ce0c/duo-client/pom.xml#L7

Thanks.

**Comment by AaronAtDuo** [comment]
@oulman Sorry about that. Seems like we overlooked a spot when we last fixed up the version numbers.  I'll have that fixed shortly.

Thanks for the heads up, and thanks for using Duo!

**Comment by AaronAtDuo** [comment]
The version numbers should now be consistent across all poms.

**Comment by oulman** [comment]
Thank you!
